remove docker env from e2e and create exit code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -211,6 +211,12 @@ jobs:
           command: |
             cd docker 
             docker-compose run fs-intake-frontend sudo yarn e2e:cidkr --environment docker
+            e2ereturncode=$?
+            if [[ $e2ereturncode = 0 ]]
+              then echo 'SUCCESS'
+            else echo 'FAIL'
+            fi
+            exit $e2ereturncode
 
   staging-deploy:
     docker:
